from utils.function_calling import ToolRegistry

# Auto-generated by Setup UI. Changes may be overwritten.
from utils.custom_functions import get_weather

TEMPLATE_REGISTRY: dict[str, str | tuple[str, callable]] = {}
TOOL_REGISTRY = ToolRegistry()

TOOL_REGISTRY.add_function(get_weather)
TEMPLATE_REGISTRY.update({
    "get_weather": "components/weather_widget.html",
})
